server:
  #  port: 8081 #for Android
  port: 8082

spring:
  datasource:
    #    url: jdbc:mysql://127.0.0.1:3306/book?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://39.108.138.143:3306/book?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: fuck@you!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/*.xml

logging:
  level:
    #打印SQL信息
    com.example.bookbackend.mapper: DEBUG

