server:
  port: 8082

spring:
  datasource:
    #    url: jdbc:mysql://127.0.0.1:3306/book?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://39.108.138.143:3306/paper?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: fuck@you!
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 39.108.138.143
    port: 6379
    password: fuck@you
    timeout: 5000
    jedis:
      pool:
        max-active: 5
        max-wait: -1
        max-idle: 4
        min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    #打印SQL信息
    com.yafeng.paperbackend.mapper: DEBUG

